### ISSUE TITLE
Finds and connects to pool, but no entities added

### ISSUE THREAD

**Issue by hacs570** [jlvaillant/intellicenter#13]
Whenever I add the integration, it finds my pool, but gives me nothing to control it with. There is no other configuration options available. 
![image](https://user-images.githubusercontent.com/83527394/116803397-e8313c80-aadc-11eb-85ad-604ebfed376d.png)

Anyone know a fix?

**Comment by hacs570** [comment]
Nevermind, I had a password enabled

**Comment by roopesh** [comment]
@hacs570 Did you have to enter a password?  I didn't see a way to configure the component.
