### ISSUE TITLE
Pin Support?

### ISSUE THREAD

**Issue by johnlento** [jlvaillant/intellicenter#27]
My IntelliCenter has security mode on and a pin set for the administrator so that someone can’t just walk to the panel and change settings. I know in the IntelliCenter app you can specify a pin when connecting. Is this a feature you do or can support?

**Comment by jlvaillant** [comment]
To my knowledge, and having tried it, the PIN only affects the mobile app and panel. The connection used by the integration is not affected so it should work either way. Is your experience any different?

**Comment by johnlento** [comment]
I am unable to connect to IntelliCenter. It just says failed to connect when I add IP address and I don’t see any entities created.


John Miles Lento Jr.
| - gpg public key: https://lento.io/08EB5F22.txt
| - Sent via RFC 1149...
________________________________

**Comment by johnlento** [comment]
This was my bad, I missed some things in the logs. Issue #5 helped me fix it. I reduced the attributes to 50 from 250 and entities are now there with pin enabled.
