### ISSUE TITLE
Not seeing Intellicenter Circuit Groups

### ISSUE THREAD

**Issue by smartqasa** [jlvaillant/intellicenter#46]
Just installed the integration. Intellicenter 1.064 with HA Core 2022.4.2 and Supervisor 2022.4.0.  Two observations:

1. Circuit groups not showing up as HA entities.
2. Hybrid heater (for UltraTemp ETi Hybrid Heater) controls not visible on HA.

**Comment by Gibby** [comment]
+1, Need circuit groups too.

Workaround, I just created them as features and setup a group in HA for now.

**Comment by jlvaillant** [comment]
yes, the idea is to make them as features. There are many "internal" circuits that I don't think should be exposed. The one you want to expose, declare them as features. Similar to the mobile apps UI IMHO.

**Comment by jlvaillant** [comment]
Regarding the Hybrid Heater, I don't have one so I don't know how it is represented internally as an object. I could work with you directly to try to reverse engineer it. Would you like to move to a separate feature request?
