### ISSUE TITLE
HACS install failure

### ISSUE THREAD

**Issue by nervling** [jlvaillant/intellicenter#53]
I'm getting the following failure in my homeassistant logs. I'm running HA via docker if that matters.

Logger: custom_components.hacs
Source: custom_components/hacs/helpers/methods/installation.py:29
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 9:34:49 AM (34 occurrences)
Last logged: 9:37:55 AM

Download was not completed [timeout() got an unexpected keyword argument 'loop']

**Comment by dwradcliffe** [comment]
I'm guessing this is either a bug in HACS or a problem with your internet connection, and not related to this component.

**Comment by nervling** [comment]
I doubt it's my internet connection, but it could be a recent HACS bug. Someone else would need to try a fresh install to see if it repros.

**Comment by nervling** [comment]
looks like my HACS was really out of date. Updating it fixed the issue. Thanks!
